spring:
  main:
    banner-mode: off
server:
  port: ${NCANODE_PORT:14589}
ncanode:
  system:
    detailedErrors: ${NCANODE_DEBUG:true}
    cacheDir: ${NCANODE_CACHE_DIR:./cache}
  crl:
    enabled: ${NCANODE_CRL_ENABLED:true}
    ttl: ${NCANODE_CRL_TTL:1440}
    url: ${NCANODE_CRL_URL:https://ca.gamma.kz/query/get-rev-list/?certType=GOST https://ca.gamma.kz/query/get-rev-list/?certType=RSA}
    delta:
      url: ${NCANODE_CRL_DELTA_URL:}
      ttl: ${NCANODE_CRL_DELTA_TTL:60}
  http-client:
    connectionTtl: ${NCANODE_HTTP_CLIENT_CONNECTION_TTL:10}
    userAgent: ${NCANODE_HTTP_CLIENT_USER_AGENT:}
    proxy:
      url: ${NCANODE_PROXY_URL:}
      username: ${NCANODE_PROXY_USERNAME:}
      password: ${NCANODE_PROXY_PASSWORD:}
  ocsp:
    url: ${NCANODE_OCSP_URL:http://ocsp.pki.gov.kz/}
  ca:
    url: ${NCANODE_CA_URL:file://resources/ca/ROOT_GOST.cer file://resources/ca/ROOT_RSA.cer}
    ttl: ${NCANODE_CA_TTL:1440}
    crl:
      enabled: ${NCANODE_CA_CRL_ENABLED:false}
      ttl: ${NCANODE_CA_CRL_TTL:1440}
      url: ${NCANODE_CA_CRL_URL:}
      delta:
        enabled: false
        url:
        ttl:
  tsp:
    url: ${NCANODE_TSP_URL:http://tsp.pki.gov.kz/}
    retries: ${NCANODE_TSP_RETRIES:3}
